'use client';

import { useState } from 'react';
import { Loader2, UserPlus } from 'lucide-react';
import Link from 'next/link';
import { readResponseJson } from '@/lib/read-response-json';

export default function CommunityRegisterPage() {
  const [form, setForm] = useState({ name: '', email: '', password: '', confirmPassword: '', acceptedPolicies: false });
  const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const checks = [form.password.length >= 8, /[a-z]/.test(form.password), /[A-Z]/.test(form.password), /\d/.test(form.password), /[^A-Za-z0-9]/.test(form.password)];
  const set = (field: string, value: string | boolean) => setForm((current) => ({ ...current, [field]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(null); setMessage(null); if (checks.some((item) => !item) || form.password !== form.confirmPassword) { setError('Use uma senha forte e confirme corretamente.'); setLoading(false); return; } const response = await fetch('/api/community/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form }) }); const data = await readResponseJson<{ error?: string }>(response); if (!response.ok) setError(data.error || 'Não foi possível criar a conta.'); else setMessage('Conta criada. Verifique seu e-mail para liberar o login.'); setLoading(false); };
  return <div className="min-h-screen flex items-center justify-center bg-zinc-100 dark:bg-zinc-950 px-4 py-8"><div className="w-full max-w-sm"><div className="bg-white dark:bg-zinc-900 rounded-xl border border-zinc-200 dark:border-zinc-800 shadow-lg p-6"><div className="text-center mb-6"><div className="w-12 h-12 rounded-xl bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center mx-auto mb-4"><UserPlus className="w-6 h-6 text-amber-500" /></div><h1 className="text-lg font-semibold text-zinc-900 dark:text-white">Criar conta da comunidade</h1><p className="text-xs text-zinc-400 mt-1">Hospede e gerencie seus ícones</p></div><form onSubmit={submit} className="space-y-4"><input required value={form.name} onChange={(e) => set('name', e.target.value)} placeholder="Nome completo" className="w-full px-3 py-2 text-sm bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-lg" /><input required type="email" value={form.email} onChange={(e) => set('email', e.target.value)} placeholder="E-mail" autoComplete="email" className="w-full px-3 py-2 text-sm bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-lg" /><input required type="password" value={form.password} onChange={(e) => set('password', e.target.value)} placeholder="Senha" autoComplete="new-password" className="w-full px-3 py-2 text-sm bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-lg" /><div className="flex gap-1">{checks.map((passed, index) => <span key={index} className={`h-1 flex-1 rounded-full ${passed ? 'bg-green-500' : 'bg-zinc-200 dark:bg-zinc-700'}`} />)}</div><input required type="password" value={form.confirmPassword} onChange={(e) => set('confirmPassword', e.target.value)} placeholder="Confirmar senha" autoComplete="new-password" className="w-full px-3 py-2 text-sm bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-lg" /><label className="flex gap-2 text-xs text-zinc-500"><input type="checkbox" checked={form.acceptedPolicies} onChange={(e) => set('acceptedPolicies', e.target.checked)} required />Aceito os termos e me responsabilizo pelos ícones enviados.</label>{error && <p className="text-xs text-red-500 bg-red-50 dark:bg-red-900/20 p-2 rounded-lg">{error}</p>}{message && <p className="text-xs text-green-600 bg-green-50 p-2 rounded-lg">{message}</p>}<button disabled={loading} className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-amber-500 hover:bg-amber-600 text-white rounded-lg text-sm font-medium disabled:opacity-50">{loading && <Loader2 className="w-4 h-4 animate-spin" />}Criar conta</button></form><p className="text-xs text-center text-zinc-500 mt-5">Já possui conta? <Link href="/community/login" className="text-blue-600 hover:underline">Entrar</Link></p></div></div></div>;
}
